language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - '.+'

install:
      - mkdir ~/.gradle
      - cp init.gradle ~/.gradle/
      # Ensure Gradle wrapper is executable, download wrapper and show version
      - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
      # Download and show android dependencies
      # - ./gradlew androidDependencies

script:
      - ./gradlew -i clean assembleDebug

cache: off

sudo: false
